# Generated by Django 5.0.9 on 2024-11-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entregable",
            name="fecha_finalizacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entregable",
            name="fecha_inicio",
            field=models.DateField(blank=True, null=True),
        ),
    ]
